# QUESTION1:

In [9]:
mylist=[]
for i in range (2000,3200):
    if (i % 7==0) and (i % 5) > 0 :
      mylist.append(i)
    
print(mylist)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


# QUESTION2:

In [25]:
def fact(x):
    f=1
    for i in range(1,x+1) :
        f=f*i
    return f 

In [28]:
# test 
factoriel=fact(5)
print (factoriel)

120


# QUESTION3

In [30]:
def new_dict (x) :
    dict={}
    for i in range(x):
        dict[i]=i*i
    return dict
      

In [31]:
new_dict (3)

{0: 0, 1: 1, 2: 4}

In [32]:
new_dict(10)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

# QUESTION4 

In [39]:
def missing_char (str , i): 
    new_str=""
    if i in range(len(str)):
     new_str=str.replace(str[i],"")
     return new_str

In [41]:
# test
missing_char ("soumia" ,2)


'somia'

# QUESTION5

In [51]:
import numpy as np 
new_array=np.array ([[1,2,3],[4,5,6],[7,8,9]]) 
print (new_array)
list1=new_array.tolist()
print (list1) 
    


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


# QUESTION6

In [60]:
a= np.array ([[1,2,3],[4,5,6],[7,8,9]]) 
b= np.array ([[9,10,11],[6,20,12],[0,3,9]])
cov=np.cov(a,b)

In [61]:
print(cov)

[[ 1.          1.          1.          1.          3.          4.5       ]
 [ 1.          1.          1.          1.          3.          4.5       ]
 [ 1.          1.          1.          1.          3.          4.5       ]
 [ 1.          1.          1.          1.          3.          4.5       ]
 [ 3.          3.          3.          3.         49.33333333  8.        ]
 [ 4.5         4.5         4.5         4.5         8.         21.        ]]


# QUESTION7

In [ ]:
import math 

def formula (D):
    H=30
    C=50
    list1=list(D.split(","))
    int_list = list(map(int, list1))
    print(int_list)
    print(type(int_list))
    l=len(int_list)
    print(l)
    j=0
    while j < (len(int_list)) :
        int_list[j]=math.sqrt((2* C * int_list[j]/H))
        print("Q",j,"=",round(int_list[j]))
        j+=1
